/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArticlesRouteImport } from './routes/articles'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ArticlesIndexRouteImport } from './routes/articles.index'
import { Route as ArticlesIdRouteImport } from './routes/articles.$id'
import { Route as ArticlesNewRouteImport } from './routes/articles.new'
import { Route as ArticlesIdEditRouteImport } from './routes/articles.$id_.edit'
import { Route as PublicArticlesIdRouteImport } from './routes/public.articles.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesRoute = ArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesIndexRoute = ArticlesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ArticlesRoute,
} as any)
const ArticlesIdRoute = ArticlesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ArticlesRoute,
} as any)
const ArticlesNewRoute = ArticlesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ArticlesRoute,
} as any)
const ArticlesIdEditRoute = ArticlesIdEditRouteImport.update({
  id: '/$id_/edit',
  path: '/$id/edit',
  getParentRoute: () => ArticlesRoute,
} as any)
const PublicArticlesIdRoute = PublicArticlesIdRouteImport.update({
  id: '/public/articles/$id',
  path: '/public/articles/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/articles': typeof ArticlesRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/articles/$id': typeof ArticlesIdRoute
  '/articles/new': typeof ArticlesNewRoute
  '/articles/': typeof ArticlesIndexRoute
  '/articles/$id/edit': typeof ArticlesIdEditRoute
  '/public/articles/$id': typeof PublicArticlesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/articles/$id': typeof ArticlesIdRoute
  '/articles/new': typeof ArticlesNewRoute
  '/articles': typeof ArticlesIndexRoute
  '/articles/$id/edit': typeof ArticlesIdEditRoute
  '/public/articles/$id': typeof PublicArticlesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/articles': typeof ArticlesRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/articles/$id': typeof ArticlesIdRoute
  '/articles/new': typeof ArticlesNewRoute
  '/articles/': typeof ArticlesIndexRoute
  '/articles/$id_/edit': typeof ArticlesIdEditRoute
  '/public/articles/$id': typeof PublicArticlesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/articles'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/articles/$id'
    | '/articles/new'
    | '/articles/'
    | '/articles/$id/edit'
    | '/public/articles/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/articles/$id'
    | '/articles/new'
    | '/articles'
    | '/articles/$id/edit'
    | '/public/articles/$id'
  id:
    | '__root__'
    | '/'
    | '/articles'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/articles/$id'
    | '/articles/new'
    | '/articles/'
    | '/articles/$id_/edit'
    | '/public/articles/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArticlesRoute: typeof ArticlesRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  PublicArticlesIdRoute: typeof PublicArticlesIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles': {
      id: '/articles'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof ArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/': {
      id: '/articles/'
      path: '/'
      fullPath: '/articles/'
      preLoaderRoute: typeof ArticlesIndexRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/articles/$id': {
      id: '/articles/$id'
      path: '/$id'
      fullPath: '/articles/$id'
      preLoaderRoute: typeof ArticlesIdRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/articles/new': {
      id: '/articles/new'
      path: '/new'
      fullPath: '/articles/new'
      preLoaderRoute: typeof ArticlesNewRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/articles/$id_/edit': {
      id: '/articles/$id_/edit'
      path: '/$id/edit'
      fullPath: '/articles/$id/edit'
      preLoaderRoute: typeof ArticlesIdEditRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/public/articles/$id': {
      id: '/public/articles/$id'
      path: '/public/articles/$id'
      fullPath: '/public/articles/$id'
      preLoaderRoute: typeof PublicArticlesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ArticlesRouteChildren {
  ArticlesIdRoute: typeof ArticlesIdRoute
  ArticlesNewRoute: typeof ArticlesNewRoute
  ArticlesIndexRoute: typeof ArticlesIndexRoute
  ArticlesIdEditRoute: typeof ArticlesIdEditRoute
}

const ArticlesRouteChildren: ArticlesRouteChildren = {
  ArticlesIdRoute: ArticlesIdRoute,
  ArticlesNewRoute: ArticlesNewRoute,
  ArticlesIndexRoute: ArticlesIndexRoute,
  ArticlesIdEditRoute: ArticlesIdEditRoute,
}

const ArticlesRouteWithChildren = ArticlesRoute._addFileChildren(
  ArticlesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArticlesRoute: ArticlesRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  PublicArticlesIdRoute: PublicArticlesIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
